#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# code style guidelines check
echo checking for code style guide violations:
sh ./make.sh lint

# automated code tests
echo running code tests
sh ./make.sh test

python -u "main.py"
